### ISSUE TITLE
Make SF commands more smart & intuitive

### ISSUE THREAD

**Issue by Snakefin** [silverfin/silverfin-vscode#9]
**Is your feature request related to a problem? Please describe.**

The Silverfin commands almost always need to be typed again, which is counter-intuitive and frustrating. 
Ofc, one can type "silverfin" and then with the arrows go through the history of already made commands, but then one still needs to erase parts of the command (eg the URL) and paste the correct one. 😵‍💫

**Describe the solution you'd like**

In SF, we all use snippets like doing if and press tab, which creates the needed output with the part selected that is mostly to be changed in the pre-formatted code snippet

It would be awesome if there was such a way in the VSC terminal, where one just types "sf_import_rt" and that's it. 

**Describe alternatives you've considered**

I've considered accepting my frustration every time I use CLI, but that doesn't seem to be healthy on my age so 😅

**Additional context**

Woet seems to know the solution we all desperately want; see [here](https://silverfin.slack.com/archives/C0376K9NNTS/p1682684490909249?thread_ts=1682684083.339899&cid=C0376K9NNTS)

**Comment by AgustinSilverfin** [comment]
FYI this issue is mostly related to the CLI and not to the VS Code extension :slightly_smiling_face: 

We have proposed the use of custom aliases to improve this situation. For example, `silverfin import-reconciliation` could be `sfir`.

We have in the pipeline another feature that could also help with this issue. A "development-mode" in the CLI, where it keeps watching for file changes and push them directly to the platform, without the need to run a new command everytime. This won't be useful for every case though (for example, it will be useful to run liquid test, or push your liquid code from your repository to the platform, but not to fetch the code using the import commands). [Link to PR](https://github.com/silverfin/sf-toolkit/pull/34)
